name: rainforest_biz_project
description: ''
version: 0.0.1
author: israel.carrillob@hsbc.com.mx
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rainforestbizproject
  parentArtefactID: israelcarrillobhsbccommxteam
  buildSystem: wheel
  author: null
  createdAt: '2025-06-05 16:44:50'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: israel.carrillob@hsbc.com.mx
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-06-05 16:44:50'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enrich_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: israel.carrillob@hsbc.com.mx
    createdAt: '2025-06-05 17:59:15'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 27910
        datasetType: Database
        description: ''
        author: israel.carrillob@hsbc.com.mx
        createdAt: '2025-06-05 17:59:15'
templates: {}
jobs:
  jobs/daily_Accounts:
    name: daily_Accounts
    description: ''
    fabricUID: 27910
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/enrich_accounts
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2025-06-07 13:17:01'
    author: israel.carrillob@hsbc.com.mx
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-06-05 16:44:50'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-06-05T16:44:50.334439Z'
  name: plibMaven
  version: 8.9.0
  id: '364669291'
  createdAt: '2025-06-05T16:44:50.334439Z'
  type: plibMaven
- modifiedAt: '2025-06-05T16:44:50.334439Z'
  name: plibPypi
  version: 1.9.49
  id: '1360606223'
  createdAt: '2025-06-05T16:44:50.334439Z'
  type: plibPypi
projectDependencies:
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2025-06-05 16:33:09'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.45
    isDefault: true
    author: null
    createdAt: '2025-06-05 16:33:09'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.9
    isDefault: true
    author: null
    createdAt: '2025-06-05 16:33:09'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
